## Preprocessing

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("/content/drive/MyDrive/DataClassNotebooks/Module_21_HW/deep-learning-challenge/Code/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
df_reduced = application_df.drop(columns = ['EIN', 'NAME', 'ORGANIZATION', 'ASK_AMT'])

df_reduced

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,1,0,N,1
1,T3,Independent,C2000,Preservation,1,1-9999,N,1
2,T5,CompanySponsored,C3000,ProductDev,1,0,N,0
3,T3,CompanySponsored,C2000,Preservation,1,10000-24999,N,1
4,T3,Independent,C1000,Heathcare,1,100000-499999,N,1
...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,1,0,N,0
34295,T4,CompanySponsored,C3000,ProductDev,1,0,N,0
34296,T3,CompanySponsored,C2000,Preservation,1,0,N,0
34297,T5,Independent,C3000,ProductDev,1,0,N,1
34298,T3,Independent,C1000,Preservation,1,1M-5M,N,0

In [4]:
# Determine the number of unique values in each column.
unique_counts = df_reduced.nunique(axis=0)
  
print("Unique values in each column :\n",
      unique_counts)

Unique values in each column :
 APPLICATION_TYPE          17
AFFILIATION                6
CLASSIFICATION            71
USE_CASE                   5
STATUS                     2
INCOME_AMT                 9
SPECIAL_CONSIDERATIONS     2
IS_SUCCESSFUL              2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
df_reduced['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T25', 'T14', 'T29', 'T15', 'T17', 'T2', 'T12', 'T13', 'T9']

# Replace in dataframe
for app in application_types_to_replace:
    df_reduced['APPLICATION_TYPE'] = df_reduced['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
df_reduced['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
df_reduced['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1

class_counts = df_reduced['CLASSIFICATION'].value_counts()

df_2 = pd.DataFrame(class_counts)
df_2.reset_index()
df_2


df_3 = df_2.loc[df_2['CLASSIFICATION'] < 50]
df_3

classifications_to_replace = df_3.index.values.tolist()

classifications_to_replace

['C1230',
 'C1400',
 'C7200',
 'C2300',
 'C1240',
 'C8000',
 'C7120',
 'C1500',
 'C1800',
 'C6000',
 'C1250',
 'C8200',
 'C1238',
 'C1278',
 'C1235',
 'C1237',
 'C7210',
 'C2400',
 'C1720',
 'C4100',
 'C1257',
 'C1600',
 'C1260',
 'C2710',
 'C0',
 'C3200',
 'C1234',
 'C1246',
 'C1267',
 'C1256',
 'C2190',
 'C4200',
 'C2600',
 'C5200',
 'C1370',
 'C1248',
 'C6100',
 'C1820',
 'C1900',
 'C1236',
 'C3700',
 'C2570',
 'C1580',
 'C1245',
 'C2500',
 'C1570',
 'C1283',
 'C2380',
 'C1732',
 'C1728',
 'C2170',
 'C4120',
 'C8210',
 'C2561',
 'C4500',
 'C2150']

In [9]:

# Replace in dataframe
for cls in classifications_to_replace:
    df_reduced['CLASSIFICATION'] = df_reduced['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
df_reduced['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      391
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
Name: CLASSIFICATION, dtype: int64

In [10]:
df_reduced

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,1,0,N,1
1,T3,Independent,C2000,Preservation,1,1-9999,N,1
2,T5,CompanySponsored,C3000,ProductDev,1,0,N,0
3,T3,CompanySponsored,C2000,Preservation,1,10000-24999,N,1
4,T3,Independent,C1000,Heathcare,1,100000-499999,N,1
...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,1,0,N,0
34295,T4,CompanySponsored,C3000,ProductDev,1,0,N,0
34296,T3,CompanySponsored,C2000,Preservation,1,0,N,0
34297,T5,Independent,C3000,ProductDev,1,0,N,1
34298,T3,Independent,C1000,Preservation,1,1M-5M,N,0

In [11]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df = pd.get_dummies(data = df_reduced, columns = ['APPLICATION_TYPE', 'CLASSIFICATION', 'INCOME_AMT', 'AFFILIATION', 'USE_CASE', 'SPECIAL_CONSIDERATIONS'])

In [12]:
dummies_df

,STATUS,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,USE_CASE_CommunityServ,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
1,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
2,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,1,0
3,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
4,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,1,0
34295,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,1,0
34296,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
34297,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,1,0
34298,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0

In [13]:
# Split our preprocessed data into our features and target arrays
X = dummies_df.drop(columns='IS_SUCCESSFUL')

y = dummies_df['IS_SUCCESSFUL']


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [15]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn_model = tf.keras.models.Sequential()




# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=48))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))

# Third hidden layer

nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))

# Fourth hidden layer

nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))

# Fifth hidden layer

nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 16)                784

 dense_1 (Dense)             (None, 16)                272

 dense_2 (Dense)             (None, 16)                272

 dense_3 (Dense)             (None, 16)                272

 dense_4 (Dense)             (None, 16)                272

 dense_5 (Dense)             (None, 1)                 17

=================================================================
Total params: 1,889
Trainable params: 1,889
Non-trainable params: 0
_________________________________________________________________

In [16]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [17]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 6s 4ms/step - loss: 0.5881 - accuracy: 0.7032
Epoch 2/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5625 - accuracy: 0.7245
Epoch 3/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5584 - accuracy: 0.7269
Epoch 4/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5566 - accuracy: 0.7287
Epoch 5/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5556 - accuracy: 0.7292
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5548 - accuracy: 0.7288
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5541 - accuracy: 0.7297
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5538 - accuracy: 0.7297
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5533 - accuracy: 0.7298
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5529 - accuracy: 0.7297
Epoch 11/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5526 - accuracy: 0.7303
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5522 - accuracy: 0.7308
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5520 - accuracy: 0.7302
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5519 - accuracy: 0.7307
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5520 - accuracy: 0.7311
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5518 - accuracy: 0.7311
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5513 - accuracy: 0.7304
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5514 - accuracy: 0.7313
Epoch 19/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5510 - accuracy: 0.7311
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7314
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5510 - accuracy: 0.7309
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7316
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5505 - accuracy: 0.7313
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5502 - accuracy: 0.7315
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5502 - accuracy: 0.7310
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7313
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5499 - accuracy: 0.7311
Epoch 28/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5498 - accuracy: 0.7313
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7310
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7318
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7325
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7307
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7314
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7326
Epoch 35/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5489 - accuracy: 0.7321
Epoch 36/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5492 - accuracy: 0.7315
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7310
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7317
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7322
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7317
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7325
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7320
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5483 - accuracy: 0.7318
Epoch 44/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5483 - accuracy: 0.7335
Epoch 45/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5484 - accuracy: 0.7319
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5485 - accuracy: 0.7327
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7314
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7317
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5481 - accuracy: 0.7315
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5480 - accuracy: 0.7319

In [18]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5612 - accuracy: 0.7317 - 847ms/epoch - 3ms/step
Loss: 0.561155378818512, Accuracy: 0.7316617965698242